import { useMemo } from 'react';
import { useSearchParams } from 'react-router-dom';
import { gameApi } from '@/shared/api/gameApi';
import { useAsyncResource } from '@/shared/hooks/useAsyncResource';
import { ErrorState, LoadingState } from '@/shared/ui/ResourceState';
import { SAMPLE_RUN_ID } from '../model/constants';

export function RunSummaryPage() {
  const [searchParams] = useSearchParams();
  const runId = useMemo(() => searchParams.get('runId') ?? SAMPLE_RUN_ID, [searchParams]);

  const runSummary = useAsyncResource(() => gameApi.getRunSummary(runId), [runId]);

  return (
    <section>
      <h2>Run Summary</h2>
      <p>Run detail is loaded from the persisted <code>/api/runs/{`{id}`}</code> backend endpoint.</p>

      {runSummary.isLoading && <LoadingState label="run summary" />}
      {runSummary.error && (
        <ErrorState
          title="Run summary unavailable"
          message={`Run ${runId} could not be loaded. Ensure the run ID exists and backend services are running.`}
        />
      )}

      {runSummary.data && (
        <div className="panel">
          <p>Run ID: {runSummary.data.id}</p>
          <ul>
            <li>Nickname: {runSummary.data.nicknameSnapshot}</li>
            <li>Processed Data: {runSummary.data.processedCount}</li>
            <li>Wave Reached: {runSummary.data.waveReached}</li>
            <li>Survival Time: {runSummary.data.survivalSeconds}s</li>
            <li>Difficulty: {runSummary.data.difficulty}</li>
            <li>Mode: {runSummary.data.mode}</li>
            <li>Score: {runSummary.data.score}</li>
            <li>Validation: {runSummary.data.suspicious ? `Flagged (${runSummary.data.validationNotes ?? 'No notes'})` : 'Clean'}</li>
          </ul>
        </div>
      )}

      <div className="panel">
        Tip: append <code>?runId=&lt;uuid&gt;</code> to this route once run IDs are generated by gameplay submission.
      </div>
    </section>
  );
}
